/*
 * Diffbot Enhance Service
 * Enhance is an API to find a person or organization in the Knowledge Graph using partial data
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: support@diffbot.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.diffbot.kg.enhance.openapi.api;

import com.diffbot.kg.enhance.openapi.invoker.ApiException;
import com.diffbot.kg.enhance.openapi.model.EnhanceResponse;
import com.diffbot.kg.enhance.openapi.model.RequestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnhanceLiveEndpointApi
 */
@Ignore
public class EnhanceLiveEndpointApiTest {

    private final EnhanceLiveEndpointApi api = new EnhanceLiveEndpointApi();

    
    /**
     * Live Enhance Endpoint
     *
     * Enhance endpoint to find person or organization using partial data
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enhanceTest() throws ApiException {
        String token = null;
        String type = null;
        String id = null;
        String name = null;
        String url = null;
        String phone = null;
        String email = null;
        String description = null;
        String employer = null;
        String title = null;
        String school = null;
        String location = null;
        String mode = null;
        String nonCanonicalFacts = null;
        String jsonmode = null;
        String rocketReachToken = null;
        String xDiffbotRequestId = null;
        EnhanceResponse response = api.enhance(token, type, id, name, url, phone, email, description, employer, title, school, location, mode, nonCanonicalFacts, jsonmode, rocketReachToken, xDiffbotRequestId);

        // TODO: test validations
    }
    
}
