/*
 * Diffbot Enhance Service
 * Enhance is an API to find a person or organization in the Knowledge Graph using partial data
 *
 * The version of the OpenAPI document: v3.0.0
 * Contact: support@diffbot.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.diffbot.kg.enhance.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BulkjobStatus
 */
public class BulkjobStatusTest {
    private final BulkjobStatus model = new BulkjobStatus();

    /**
     * Model tests for BulkjobStatus
     */
    @Test
    public void testBulkjobStatus() {
        // TODO: test BulkjobStatus
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'jobsTotal'
     */
    @Test
    public void jobsTotalTest() {
        // TODO: test jobsTotal
    }

    /**
     * Test the property 'jobsCompleted'
     */
    @Test
    public void jobsCompletedTest() {
        // TODO: test jobsCompleted
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'estimateRemainingTime'
     */
    @Test
    public void estimateRemainingTimeTest() {
        // TODO: test estimateRemainingTime
    }

}
