/*
 * Diffbot Enhance Service
 * Enhance is an API to find a person or organization in the Knowledge Graph using partial data
 *
 * The version of the OpenAPI document: v3.0.0
 * Contact: support@diffbot.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.diffbot.kg.enhance.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.diffbot.kg.enhance.openapi.model.BulkjobStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BulkjobStatusResponse
 */

public class BulkjobStatusResponse {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private BulkjobStatus content;


  public BulkjobStatusResponse code(Integer code) {
    
    this.code = code;
    return this;
  }

   /**
   * Bulkjob status code (same as the HTTP status code)
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Bulkjob status code (same as the HTTP status code)")

  public Integer getCode() {
    return code;
  }


  public void setCode(Integer code) {
    this.code = code;
  }


  public BulkjobStatusResponse content(BulkjobStatus content) {
    
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BulkjobStatus getContent() {
    return content;
  }


  public void setContent(BulkjobStatus content) {
    this.content = content;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkjobStatusResponse bulkjobStatusResponse = (BulkjobStatusResponse) o;
    return Objects.equals(this.code, bulkjobStatusResponse.code) &&
        Objects.equals(this.content, bulkjobStatusResponse.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkjobStatusResponse {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

